title: Micropub Content
url: https://muan.github.io/micropub-content
micropub_endpoint: https://micropub-endpoint-demo.herokuapp.com/micropub

timezone: GMT
permalink: /posts/:title
kramdown:
  hard_wrap: true
